plugins:
  - bsmu.retinal_fundus.plugins.main_window.RetinalFundusMainWindowPlugin:
      replace: bsmu.vision.plugins.windows.main.MainWindowPlugin
      alias: main_window
  - bsmu.retinal_fundus.plugins.table_visualizer.RetinalFundusTableVisualizerPlugin
  - bsmu.retinal_fundus.plugins.histogram_visualizer.RetinalFundusHistogramVisualizerPlugin
  - bsmu.retinal_fundus.plugins.disk_region_selector.RetinalFundusDiskRegionSelectorPlugin
  - bsmu.retinal_fundus.plugins.ms_predictor.RetinalFundusMsPredictorPlugin

  - bsmu.vision.plugins.file_dropper.FileDropperPlugin
  - bsmu.vision.plugins.loaders.image.simple.SimpleImageFileLoaderPlugin
  - bsmu.vision.plugins.post_load_converters.image_to_layered.ImageToLayeredImagePostLoadConverterPlugin
#  - bsmu.vision.plugins.visualizers.image.layered.LayeredImageVisualizerPlugin
  - bsmu.vision.plugins.layer_controller.MdiImageViewerLayerControllerPlugin
  - bsmu.vision.plugins.layers_view.LayersTableViewPlugin

#  - bsmu.vision.plugins.walkers.file.MdiImageLayerFileWalkerPlugin
#  - bsmu.vision.plugins.tools.viewer.image.smart_brush.SmartBrushImageViewerToolPlugin
#  - bsmu.vision.plugins.overlayers.path.ImageViewerPathOverlayerPlugin
#  - bsmu.vision.plugins.overlayers.intersection.ImageViewerIntersectionOverlayerPlugin
